apiVersion: v2
name: deployment
description: A Helm chart for deploying k8s deployment
type: application
dependencies:
  - name: common
    repository: https://ndustrialio.github.io/charts
    version: 0.2.4
    tags:
      - ndustrial-common
maintainers:
  - email: devops@ndustrial.io
    name: DevOps
# Please make sure that version and appVersion are always the same.
version: 0.1.24
appVersion: 0.1.24
