replicaCount: 2

service:
  type: NodePort

ingress:
  enabled: true
  hostname: null
  path: /
  pathType: Prefix
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443, "HTTP":80}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"

image:
  registry: quay.io
  pullSecrets:
    - nio-quay-pull-secret

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi

updateStrategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

ports:
  - containerPort: 3000
    name: http
    protocol: TCP
  - containerPort: 3000
    name: https
    protocol: TCP

livenessProbe:
  enabled: true
  path: /healthz

readinessProbe:
  enabled: true
  path: /healthz

datadog:
  apm:
    enabled: true
    profiling_enabled: true
