kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "postgres.names.release" . }}
  labels: 
    {{ include "postgres.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: primary
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "postgres.names.release" . }}
      app.kubernetes.io/name: {{ include "postgres.names.release" . }}
      app.kubernetes.io/component: primary
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 5432
