apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nio-common.names.fullname" . }}
  labels: 
    {{ include "postgres.labels.standard" }}
    app.kubernetes.io/component: primary
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "nio-common.names.fullname" . }}
      app.kubernetes.io/component: primary
