apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nio-common.names.fullname" . }}
  labels: 
    {{ include "postgres.labels.standard" . | nindent 4 }}
automountServiceAccountToken: false
