apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.names.release" . }}-hl
  labels:
    {{ include "postgres.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: ClusterIP
  clusterIP: None
  # We want all pods in the StatefulSet to have their addresses published for
  # the sake of the other Postgresql pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: {{ include "postgres.names.release" . }}
    app.kubernetes.io/name: {{ include "postgres.names.release" . }}
    app.kubernetes.io/component: primary
