{{- if .Values.externalSecrets }}
{{- range .Values.externalSecrets }}
{{ $path := required "A valid external secret path is required." .path}}
{{ $secret := default (printf "%s" $path | replace "/" "-" | trunc 63) .secret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret }}
  labels: {{- include "nio-common.labels.standard" $ | nindent 4 }}
    ndustrial.io/component: statefulset
    {{- if $.Values.labels }}
    {{- include "nio-common.tplvalues.render" (dict "value" $.Values.labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if $.Values.annotations }}
  annotations: {{- toYaml $.Values.annotations | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: {{ default "vault-backend" .provider }}
    kind: {{ default "ClusterSecretStore" .storeKind }}
  target:
    name: {{ $secret }}
  dataFrom:
    - extract:
        key: {{ $path }}
---
{{- end }}
{{- end }}