{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    ndustrial.io/component: statefulset
  {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ template "statefulset.serviceAccountName" . }}
  {{- $mergedAnnotations := merge .Values.serviceAccount.annotations .Values.annotations }}
  {{- if $mergedAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $mergedAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
automountServiceAccountToken: true
{{- end }}
