nameOverride: ""
fullnameOverride: ""

# Docker image
image:
  repository: quay.io/ndustrialio/cronjobexample
  pullPolicy: IfNotPresent
  pullSecret: contxt-image-pull-secret-ndustrial-auth
  tag: "" # defaults to chart appVersion

# Job's config
clientId: 
clientSecret: 
schedule: 0 0 * * * # midnight UTC, daily
args: []

# Pod's extra environment
extraEnv: []

# Pod's resource limits
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi
