{{- if .Values.externalSecrets }}
{{- range .Values.externalSecrets }}
{{- $externalSecret := merge (dict "template" .template) (fromYaml (tpl (toYaml (omit . "template" )) $)) -}}
{{- if $externalSecret.path }}
{{- $_ := set $externalSecret "secret" (default (printf "%s" $externalSecret.path | replace "/" "-" | trunc 63) $externalSecret.secret) }}
{{- else }}
{{- $_ := set $externalSecret "secret" (required "A secret is required when not passing path." $externalSecret.secret) }}
{{- $_ := set $externalSecret "properties" (required "A property list is required when not passing path." $externalSecret.properties) }}
{{- end }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.secret }}
  labels: {{- include "nio-common.labels.standard" $ | nindent 4 }}
    ndustrial.io/component: daemonset
    {{- if $.Values.labels }}
    {{- include "nio-common.tplvalues.render" (dict "value" $.Values.labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if $.Values.annotations }}
  annotations: {{- toYaml $.Values.annotations | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: {{ default "vault-backend" $externalSecret.provider }}
    kind: {{ default "ClusterSecretStore" $externalSecret.storeKind }}
  target:
    name: {{ $externalSecret.secret }}
    {{- if $externalSecret.template }}
    template:
      data: {{- tpl $externalSecret.template $ | nindent 8 -}}
    {{- end }}
  {{- if $externalSecret.path }}
  dataFrom:
    - extract:
        key: {{ $externalSecret.path }}
  {{- end }}
  {{- if $externalSecret.properties }}
  data:
    {{- range $externalSecret.properties }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ .sourceKey }}
        property: {{ default (.name) (.sourceProp) }}
    {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}