{{- if .Values.ingress.enabled }}
apiVersion: {{ include "nio-common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "nio-common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "nio-common.labels.standard" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- include "nio-common.tplvalues.render" ( dict "value" .Values.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.ingress.annotations .Values.annotations .Values.ingress.certManager }}
  annotations:
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- include "nio-common.tplvalues.render" ( dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.annotations }}
    {{- include "nio-common.tplvalues.render" ( dict "value" .Values.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if and .Values.ingress.ingressClassName (eq "true" (include "nio-common.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ include "nio-common.tplvalues.render" ( dict "value" .Values.ingress.hostname "context" $ ) }}
      http:
        paths:
          {{- if .Values.ingress.extraPaths }}
          {{- toYaml .Values.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.ingress.path }}
            {{- if eq "true" (include "nio-common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.ingress.pathType }}
            {{- end }}
            backend: {{- include "nio-common.ingress.backend" (dict "serviceName" (include "nio-common.names.fullname" .) "servicePort" "http" "context" $)  | nindent 14 }}
    {{- end }}
    {{- range .Values.ingress.extraHosts }}
    {{- if and (hasKey . "tlsOnly") (not .tlsOnly) }}
    - host: {{ include "nio-common.tplvalues.render" ( dict "value" .name "context" $ ) | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "nio-common.ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend: {{- include "nio-common.ingress.backend" (dict "serviceName" (include "nio-common.names.fullname" $) "servicePort" "http" "context" $) | nindent 14 }}
    {{- end }}
    {{- end }}
  {{- if or (and .Values.ingress.tls (or .Values.ingress.certManager .Values.ingress.selfSigned)) .Values.ingress.extraTls }}
  tls:
    {{- if and .Values.ingress.tls (or .Values.ingress.certManager .Values.ingress.selfSigned) }}
    - hosts:
        - {{ include "nio-common.tplvalues.render" ( dict "value" .Values.ingress.hostname "context" $ ) | quote }}
        {{- range .Values.ingress.extraHosts }}
        - {{ include "nio-common.tplvalues.render" ( dict "value" .name "context" $ ) | quote }}
        {{- end }}
      secretName: {{ printf "%s-tls" (include "nio-common.tplvalues.render" ( dict "value" .Values.ingress.hostname "context" $ )) }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- include "nio-common.tplvalues.render" (dict "value" .Values.ingress.extraTls "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
