{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ default (include "nio-common.names.fullname" .) .Values.gateway.nameOverride }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nio-common.labels.standard" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- include "nio-common.tplvalues.render" (dict "value" .Values.labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.gateway.annotations }}
  annotations:
    {{- include "nio-common.tplvalues.render" (dict "value" .Values.gateway.annotations "context" $) | nindent 4 }}
  {{- end }}

spec:
  gatewayClassName: {{ .Values.gateway.className | quote }}

  listeners:
    {{- range $name, $listener := .Values.gateway.listeners }}
    - name: {{ $name }}
      port: {{ $listener.port }}
      protocol: {{ $listener.protocol }}
      {{- if $listener.hostname }}
      hostname: {{ $listener.hostname | quote }}
      {{- end }}
      {{- if $listener.tls }}
      tls:
        {{- toYaml $listener.tls | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
