{{- if .Values.podDisruptionBudget.enabled }}
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata:
  name: {{ include "nio-common.names.fullname" . }}-deployment
  labels: {{- include "nio-common.labels.standard" . | nindent 4 }}
    ndustrial.io/component: deployment
    {{- if .Values.labels }}
      {{- include "nio-common.tplvalues.render" (dict "value" .Values.labels "context" $) | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels: {{- include "nio-common.labels.matchLabels" . | nindent 6 }}
      ndustrial.io/component: deployment
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
