apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.names.release" . }}
  labels: {{ include "postgres.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "nio-common.names.fullname" . }}
    app.kubernetes.io/component: primary
