## ndustrial/common
## It is required by CI/CD tools and processes.
exampleValue: common-chart

ndustrial:
  ## @param ndustrial.name The name of the application (Required)
  name:
  ## @param ndustrial.organization The slug of the Organization that owns the application (Required)
  organization:
  ## @param ndustrial.owner The service which manages the kubernetes object Should most likely be one of: helm, contxt, fleet. (Required)
  owner:
  ## @param ndustrial.env The environment being deployed into Should most likely be one of: dev, staging, prod, or qa. (Required)
  env:
  ## @param ndustrial.version The app version being deployed
  version:
contxt:
  ## @param contxt.stackId The ID of the Contxt Stack that this object belongs to (if applicable)
  stackId:
  ## @param contxt.serviceId The ID of the Contxt Service that this object belongs to (if applicable)
  serviceId:
  ## @param contxt.serviceType The type of the Contxt Service that this object belongs to (if applicable)
  serviceType:
