## ndustrial/common
## It is required by CI/CD tools and processes.
exampleValue: common-chart

ndustrial:
  ## @param ndustrial.project Unique project id that this repository belongs too (Required) aka. Project slug
  project:
  ## @param ndustrial.name The name of the application/service. (Required)
  # Should match git repository name (if able)
  name:
  ## @param ndustrial.type The service type of this deployment (api, database, backend, frontend, etl, etc...) (Required)
  type:

  ## @param ndustrial.organization The slug of the Organization that owns the application (Required)
  organization:
  ## @param ndustrial.owner The person/team that owns this service. (Required)
  owner:
  ## @param ndustrial.managed_by The service which manages the kubernetes object Should most likely be one of: helm, contxt, fleet. (Required)
  managed_by:
  ## @param ndustrial.env The environment being deployed into Should most likely be one of: dev, staging, prod, or qa. (Required)
  env:
  ## @param ndustrial.version The app version being deployed (Required)
  version:

  ## @param ndustrial.repo The github repository where the code exists (populated by CI/CD)
  repo:

  ## @param ndustrial.depends [array] List of projects/services this serivce depends on
  ## @param ndustrial.depends.0.project [string] The name of the project that this service depends on
  ## @param ndustrial.depends.0.name [string] The name of the project service
  depends: []

contxt:
  ## @param contxt.projectId The ID of the Contxt Stack that this object belongs to (if applicable)
  projectId:
  ## @param contxt.serviceId The ID of the Contxt Service that this object belongs to (if applicable)
  serviceId:
  ## @param contxt.serviceType The type of the Contxt Service that this object belongs to (if applicable)
  serviceType:

datadog:
  apm:
    enabled: false
