apiVersion: v1
kind: Service
metadata:
  name: {{ include "ndustrial-stateful.fullname" . }}
{{- if .Values.service.annotations }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
  labels:
    {{- include "ndustrial-stateful.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: ndustrial-stateful
  selector:
    app: {{ include "ndustrial-stateful.fullname" . }}
