apiVersion: v2
name: nio-api
description: A Helm chart for deploying k8s deployment
type: application
dependencies:
  - name: common
    # repository: file://../common
    repository: https://ndustrialio.github.io/charts
    version: ~0.2.24
    tags:
      - ndustrial-common
maintainers:
  - email: devops@ndustrial.io
    name: DevOps
# Please make sure that version and appVersion are always the same.
version: 1.0.16
appVersion: 1.0.16
